//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRGX.SIMTrax.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRGX.SIMTrax.Domain.Resource.EmailConstants", typeof(EmailConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert@sim-prgx.com.
        /// </summary>
        public static string ADMIN_EMAIL_ID {
            get {
                return ResourceManager.GetString("ADMIN_EMAIL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.office365.com.
        /// </summary>
        public static string EMAIL_HOST {
            get {
                return ResourceManager.GetString("EMAIL_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string EMAIL_NEEDS_AUTHENTICATION {
            get {
                return ResourceManager.GetString("EMAIL_NEEDS_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foyu4552.
        /// </summary>
        public static string EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string EMAIL_PORT {
            get {
                return ResourceManager.GetString("EMAIL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string EMAIL_SSLON {
            get {
                return ResourceManager.GetString("EMAIL_SSLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert@sim-prgx.com.
        /// </summary>
        public static string EMAIL_USER_ID {
            get {
                return ResourceManager.GetString("EMAIL_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIMTrax.
        /// </summary>
        public static string FROM_EMAIL_FRIST_NAME {
            get {
                return ResourceManager.GetString("FROM_EMAIL_FRIST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert@sim-prgx.com.
        /// </summary>
        public static string FROM_EMAIL_ID {
            get {
                return ResourceManager.GetString("FROM_EMAIL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string IS_EMAIL_ON {
            get {
                return ResourceManager.GetString("IS_EMAIL_ON", resourceCulture);
            }
        }
    }
}
